name: Test the program

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  pull_request:
    branches:
      - master


jobs:
  test_program:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Download dependencies
        run: go mod download && go mod tidy
      - name: Build Linux
        run: go test -v ./...
